### ISSUE TITLE
Don't know how to translate the following

### ISSUE THREAD

**Issue by comamitc** [comamitc/cljsfmt#1]
``` clj
(defn- indent-order [[key _]]
  (condp instance? key
    Symbol  (str 0 key) ;; from clojure.lang.Symbol
    Pattern (str 1 key))) ;; from java.util.regex.Pattern
```

Pattern appears that we can just port to `js/RegExp`. `Symbol` doesn't really have an equivalent in CLJS per say.

**Comment by shaunlebron** [comment]
I confirmed that `Symbol` will work as is, because it refers to `cljs.core/Symbol`.  In fact, this is how [`symbol?`](https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/cljs.core/symbolQMARK.md) is implemented.

`js/RegExp` will work too, [`re-pattern`](https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/cljs.core/re-pattern.md) runs this check in its implementation.

**Comment by comamitc** [comment]
Nice, thanks @shaunlebron oh mighty clojurescript wizard!

**Comment by shaunlebron** [comment]
ha, I didn't know this offhand.  I just typed `symbol` and `pattern` in the Dash search box for cljs.  the docs there are really handy
